/*
============================================================================
  Script: 02_SECUENCIAS.sql
  Descripcion: Creacion de secuencias para todas las tablas del sistema
  Proyecto: Plataforma eSports - Base de datos OLTP
  Fecha: 16/Marzo/2026
============================================================================
*/

-- =========================================================================
-- SECUENCIAS PARA CATALOGOS
-- =========================================================================
CREATE SEQUENCE SEQ_CATALOGO_AVATAR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_ESTADO_AMISTAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_ESTADO_INSCRIPCION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_ESTADO_TORNEO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_GENERO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_ORIGEN_TRANSACCION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_PLATAFORMA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_REGION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_ROL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_TIPO_ENTRADA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_TIPO_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_TIPO_TORNEO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATALOGO_TRANSACCION_TIPO START WITH 1 INCREMENT BY 1 NOCACHE;

-- =========================================================================
-- SECUENCIAS PARA TABLAS PRINCIPALES
-- =========================================================================
CREATE SEQUENCE SEQ_MEMBRESIA_TIPO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOGRO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PERSONA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EQUIPO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EQUIPO_MIEMBROS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JUEGO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MODO_JUEGO START WITH 1 INCREMENT BY 1 NOCACHE;

-- =========================================================================
-- SECUENCIAS PARA TABLAS DE TIENDA
-- =========================================================================
CREATE SEQUENCE SEQ_TIENDA_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIENDA_ORDEN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIENDA_SOLICITUD_SOPORTE START WITH 1 INCREMENT BY 1 NOCACHE;

-- =========================================================================
-- SECUENCIAS PARA TABLAS DE TORNEOS
-- =========================================================================
CREATE SEQUENCE SEQ_TORNEO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TORNEO_INSCRIPCION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TORNEO_PREMIOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TORNEO_REDES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TORNEO_RESULTADOS START WITH 1 INCREMENT BY 1 NOCACHE;

-- =========================================================================
-- SECUENCIAS PARA TABLAS DE USUARIO
-- =========================================================================
CREATE SEQUENCE SEQ_TRANSACCION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_AMIGOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_CUENTA_JUEGO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_ESTADISTICAS_JUEGO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_LOGROS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_MEMBRESIAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_RED_SOCIAL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_SEGUIDORES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USUARIO_TROFEOS START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT >>> Secuencias creadas exitosamente <<<
