/*
============================================================================
  Script: 03_TABLAS.sql
  Descripcion: Creacion de todas las tablas del sistema eSports (39 tablas)
               Convertido de PostgreSQL a Oracle PL/SQL
  Proyecto: Plataforma eSports - Base de datos OLTP
  Fecha: 16/Marzo/2026
  Notas: 
    - UUID de PostgreSQL reemplazado por NUMBER + secuencias
    - timestamp sin time zone -> TIMESTAMP
    - character varying -> VARCHAR2
    - boolean -> NUMBER(1) con CHECK (0,1)
    - jsonb -> CLOB
    - text -> CLOB
    - numeric(12,2) -> NUMBER(12,2)
    - DEFAULT now() -> DEFAULT SYSTIMESTAMP
============================================================================
*/

-- =========================================================================
-- TABLAS DE CATALOGOS (15 tablas)
-- =========================================================================

CREATE TABLE CATALOGO_AVATAR (
    ID              NUMBER          NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    URL             VARCHAR2(500)   NOT NULL,
    SEED            VARCHAR2(200)   NOT NULL,
    CATEGORIA       VARCHAR2(100),
    DISPONIBLE      NUMBER(1)       DEFAULT 1 NOT NULL,
    PREMIUM         NUMBER(1)       DEFAULT 0 NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_AVATAR PRIMARY KEY (ID),
    CONSTRAINT UQ_CATALOGO_AVATAR_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_AVATAR_DISPONIBLE CHECK (DISPONIBLE IN (0, 1)),
    CONSTRAINT CK_AVATAR_PREMIUM CHECK (PREMIUM IN (0, 1))
);

CREATE TABLE CATALOGO_ESTADO_AMISTAD (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_ESTADO_AMISTAD PRIMARY KEY (ID),
    CONSTRAINT UQ_ESTADO_AMISTAD_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_ESTADO_INSCRIPCION (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_ESTADO_INSCRIPCION PRIMARY KEY (ID),
    CONSTRAINT UQ_ESTADO_INSCRIPCION_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_ESTADO_TORNEO (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_ESTADO_TORNEO PRIMARY KEY (ID),
    CONSTRAINT UQ_ESTADO_TORNEO_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_GENERO (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_GENERO PRIMARY KEY (ID),
    CONSTRAINT UQ_GENERO_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_ORIGEN_TRANSACCION (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_ORIGEN_TRANSACCION PRIMARY KEY (ID),
    CONSTRAINT UQ_ORIGEN_TRANSACCION_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_PLATAFORMA (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_PLATAFORMA PRIMARY KEY (ID),
    CONSTRAINT UQ_PLATAFORMA_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_REGION (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(200)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_REGION PRIMARY KEY (ID),
    CONSTRAINT UQ_REGION_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_ROL (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_ROL PRIMARY KEY (ID),
    CONSTRAINT UQ_ROL_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_TIPO_ENTRADA (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_TIPO_ENTRADA PRIMARY KEY (ID),
    CONSTRAINT UQ_TIPO_ENTRADA_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_TIPO_ITEM (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_TIPO_ITEM PRIMARY KEY (ID),
    CONSTRAINT UQ_TIPO_ITEM_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_TIPO_TORNEO (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    DESCRIPCION     CLOB,
    TIPO_TROFEO     VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_TIPO_TORNEO PRIMARY KEY (ID),
    CONSTRAINT UQ_TIPO_TORNEO_VALOR UNIQUE (VALOR)
);

CREATE TABLE CATALOGO_TRANSACCION_TIPO (
    ID              NUMBER          NOT NULL,
    VALOR           VARCHAR2(100)   NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CATALOGO_TRANSACCION_TIPO PRIMARY KEY (ID),
    CONSTRAINT UQ_TRANSACCION_TIPO_VALOR UNIQUE (VALOR)
);

CREATE TABLE MEMBRESIA_TIPO (
    ID              NUMBER          NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    PRECIO          NUMBER(12,2)    NOT NULL,
    DURACION_DIAS   NUMBER          NOT NULL,
    BENEFICIOS      CLOB,
    CONSTRAINT PK_MEMBRESIA_TIPO PRIMARY KEY (ID)
);

CREATE TABLE LOGRO (
    ID              NUMBER          NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     CLOB,
    CONSTRAINT PK_LOGRO PRIMARY KEY (ID)
);


-- =========================================================================
-- TABLAS PRINCIPALES (24 tablas transaccionales + relaciones)
-- =========================================================================

CREATE TABLE PERSONA (
    ID                  NUMBER          NOT NULL,
    P_NOMBRE            VARCHAR2(100)   NOT NULL,
    S_NOMBRE            VARCHAR2(100),
    P_APELLIDO          VARCHAR2(100)   NOT NULL,
    S_APELLIDO          VARCHAR2(100),
    CORREO              VARCHAR2(200)   NOT NULL,
    FECHA_NACIMIENTO    DATE,
    TIMEZONE            VARCHAR2(100),
    CORREO_PAYPAL       VARCHAR2(200),
    TELEFONO            VARCHAR2(50),
    DIRECCION           VARCHAR2(300),
    CIUDAD              VARCHAR2(100),
    ESTADO              VARCHAR2(100),
    CODIGO_POSTAL       VARCHAR2(20),
    PAIS                VARCHAR2(100),
    DIVISA              VARCHAR2(10)    DEFAULT 'USD',
    CREADO_EN           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    GENERO_ID           NUMBER,
    CONSTRAINT PK_PERSONA PRIMARY KEY (ID),
    CONSTRAINT UQ_PERSONA_CORREO UNIQUE (CORREO),
    CONSTRAINT FK_PERSONA_GENERO FOREIGN KEY (GENERO_ID) 
        REFERENCES CATALOGO_GENERO (ID)
);

CREATE TABLE USUARIO (
    ID                      NUMBER          NOT NULL,
    NICKNAME                VARCHAR2(100)   NOT NULL,
    PASSWORD                VARCHAR2(300)   NOT NULL,
    ESTADO                  VARCHAR2(50)    DEFAULT 'activo' NOT NULL,
    ULTIMA_CONEXION         TIMESTAMP,
    XP                      NUMBER          DEFAULT 0 NOT NULL,
    SALDO                   NUMBER(12,2)    DEFAULT 0 NOT NULL,
    CREDITOS                NUMBER          DEFAULT 0 NOT NULL,
    FOTO_PERFIL             VARCHAR2(500),
    BIOGRAFIA               VARCHAR2(300),
    DESAFIOS_HABILITADOS    NUMBER(1)       DEFAULT 1 NOT NULL,
    CREADO_EN               TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT              TIMESTAMP,
    PERSONA_ID              NUMBER,
    ROL_ID                  NUMBER          NOT NULL,
    AVATAR_ID               NUMBER,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
    CONSTRAINT UQ_USUARIO_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT UQ_USUARIO_PERSONA UNIQUE (PERSONA_ID),
    CONSTRAINT CK_USUARIO_DESAFIOS CHECK (DESAFIOS_HABILITADOS IN (0, 1)),
    CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (PERSONA_ID) 
        REFERENCES PERSONA (ID),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROL_ID) 
        REFERENCES CATALOGO_ROL (ID),
    CONSTRAINT FK_USUARIO_AVATAR FOREIGN KEY (AVATAR_ID) 
        REFERENCES CATALOGO_AVATAR (ID)
);
CREATE INDEX IDX_USUARIO_PERSONA ON USUARIO(PERSONA_ID);

CREATE TABLE EQUIPO (
    ID              NUMBER          NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     CLOB,
    AVATAR_URL      VARCHAR2(500),
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREADO_POR      NUMBER,
    CONSTRAINT PK_EQUIPO PRIMARY KEY (ID),
    CONSTRAINT UQ_EQUIPO_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT FK_EQUIPO_CREADOR FOREIGN KEY (CREADO_POR) 
        REFERENCES USUARIO (ID)
);

CREATE TABLE EQUIPO_MIEMBROS (
    ID              NUMBER          NOT NULL,
    ROL             VARCHAR2(50)    DEFAULT 'miembro' NOT NULL,
    JOINED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    EQUIPO_ID       NUMBER,
    USUARIO_ID      NUMBER,
    CONSTRAINT PK_EQUIPO_MIEMBROS PRIMARY KEY (ID),
    CONSTRAINT FK_EQUIPO_MIEMBROS_EQUIPO FOREIGN KEY (EQUIPO_ID) 
        REFERENCES EQUIPO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_EQUIPO_MIEMBROS_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID)
);

CREATE TABLE JUEGO (
    ID              NUMBER          NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     CLOB,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JUEGO PRIMARY KEY (ID),
    CONSTRAINT UQ_JUEGO_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE JUEGO_PLATAFORMAS (
    JUEGO_ID                NUMBER  NOT NULL,
    CATALOGO_PLATAFORMA_ID  NUMBER  NOT NULL,
    CONSTRAINT PK_JUEGO_PLATAFORMAS PRIMARY KEY (JUEGO_ID, CATALOGO_PLATAFORMA_ID),
    CONSTRAINT FK_JUEGO_PLAT_JUEGO FOREIGN KEY (JUEGO_ID) 
        REFERENCES JUEGO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_JUEGO_PLAT_PLAT FOREIGN KEY (CATALOGO_PLATAFORMA_ID) 
        REFERENCES CATALOGO_PLATAFORMA (ID) ON DELETE CASCADE
);
CREATE INDEX IDX_JUEGO_PLAT_JUEGO ON JUEGO_PLATAFORMAS(JUEGO_ID);
CREATE INDEX IDX_JUEGO_PLAT_PLAT ON JUEGO_PLATAFORMAS(CATALOGO_PLATAFORMA_ID);

CREATE TABLE MODO_JUEGO (
    ID              NUMBER          NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     CLOB,
    JUEGO_ID        NUMBER,
    CONSTRAINT PK_MODO_JUEGO PRIMARY KEY (ID),
    CONSTRAINT FK_MODO_JUEGO_JUEGO FOREIGN KEY (JUEGO_ID) 
        REFERENCES JUEGO (ID) ON DELETE CASCADE
);

CREATE TABLE TIENDA_ITEM (
    ID                  NUMBER          NOT NULL,
    NOMBRE              VARCHAR2(200)   NOT NULL,
    DESCRIPCION         CLOB,
    PRECIO              NUMBER(12,2)    NOT NULL,
    CREDITOS_OTORGADOS  NUMBER,
    METADATA            CLOB,
    TIPO_ID             NUMBER          NOT NULL,
    CONSTRAINT PK_TIENDA_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_TIENDA_ITEM_TIPO FOREIGN KEY (TIPO_ID) 
        REFERENCES CATALOGO_TIPO_ITEM (ID)
);

CREATE TABLE TIENDA_ORDEN (
    ID                  NUMBER          NOT NULL,
    PAYPAL_ORDER_ID     VARCHAR2(200),
    PAYPAL_CAPTURE_ID   VARCHAR2(200),
    PAYPAL_PAYER_ID     VARCHAR2(200),
    PAYPAL_PAYER_EMAIL  VARCHAR2(200),
    MONTO               NUMBER(12,2)    NOT NULL,
    DIVISA              VARCHAR2(3)     DEFAULT 'USD' NOT NULL,
    ESTADO              VARCHAR2(50)    DEFAULT 'pendiente' NOT NULL,
    METADATA            CLOB            DEFAULT '{}',
    CREADO_EN           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETADO_EN       TIMESTAMP,
    ACTUALIZADO_EN      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_ID          NUMBER          NOT NULL,
    ITEM_ID             NUMBER          NOT NULL,
    CONSTRAINT PK_TIENDA_ORDEN PRIMARY KEY (ID),
    CONSTRAINT FK_TIENDA_ORDEN_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TIENDA_ORDEN_ITEM FOREIGN KEY (ITEM_ID) 
        REFERENCES TIENDA_ITEM (ID)
);

CREATE TABLE TIENDA_SOLICITUD_SOPORTE (
    ID                      NUMBER          NOT NULL,
    TIPO                    VARCHAR2(50)    NOT NULL,
    NICKNAME_SOLICITADO     VARCHAR2(100),
    ESTADO                  VARCHAR2(50)    DEFAULT 'pendiente' NOT NULL,
    NOTAS_ADMIN             CLOB,
    CREADO_EN               TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    RESUELTO_EN             TIMESTAMP,
    ORDEN_ID                NUMBER,
    USUARIO_ID              NUMBER          NOT NULL,
    RESUELTO_POR            NUMBER,
    CONSTRAINT PK_TIENDA_SOLICITUD_SOPORTE PRIMARY KEY (ID),
    CONSTRAINT FK_SOLICITUD_ORDEN FOREIGN KEY (ORDEN_ID) 
        REFERENCES TIENDA_ORDEN (ID) ON DELETE SET NULL,
    CONSTRAINT FK_SOLICITUD_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SOLICITUD_RESUELTO_POR FOREIGN KEY (RESUELTO_POR) 
        REFERENCES USUARIO (ID)
);
CREATE INDEX IDX_SOLICITUD_USUARIO ON TIENDA_SOLICITUD_SOPORTE(USUARIO_ID);

CREATE TABLE TORNEO (
    ID                          NUMBER          NOT NULL,
    TITULO                      VARCHAR2(300)   NOT NULL,
    DESCRIPCION                 CLOB,
    FECHA_INICIO_REGISTRO       TIMESTAMP,
    FECHA_FIN_REGISTRO          TIMESTAMP,
    FECHA_INICIO_TORNEO         TIMESTAMP,
    TIPO_TORNEO                 VARCHAR2(100),
    AL_MEJOR_DE                 NUMBER          DEFAULT 1 NOT NULL,
    FORMATO                     VARCHAR2(100),
    CERRADO                     NUMBER(1)       DEFAULT 0 NOT NULL,
    REGLAS                      CLOB,
    JUGADORES_PC_PERMITIDOS     NUMBER(1)       DEFAULT 1 NOT NULL,
    REQUIERE_TRANSMISION        NUMBER(1)       DEFAULT 0 NOT NULL,
    REQUIERE_CAMARA             NUMBER(1)       DEFAULT 0 NOT NULL,
    CAPACIDAD                   NUMBER,
    BANNER_URL                  VARCHAR2(500),
    MINIATURA_URL               VARCHAR2(500),
    CONTACTO_ANFITRION          VARCHAR2(200),
    DISCORD_SERVIDOR            VARCHAR2(200),
    CREADO_EN                   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ANFITRION_ID                NUMBER          NOT NULL,
    JUEGO_ID                    NUMBER,
    PLATAFORMA_ID               NUMBER,
    MODO_JUEGO_ID               NUMBER,
    REGION_ID                   NUMBER          NOT NULL,
    ESTADO_ID                   NUMBER,
    TIPO_TORNEO_ID              NUMBER,
    TIPO_ENTRADA_ID             NUMBER          NOT NULL,
    CONSTRAINT PK_TORNEO PRIMARY KEY (ID),
    CONSTRAINT CK_TORNEO_CERRADO CHECK (CERRADO IN (0, 1)),
    CONSTRAINT CK_TORNEO_PC CHECK (JUGADORES_PC_PERMITIDOS IN (0, 1)),
    CONSTRAINT CK_TORNEO_TRANS CHECK (REQUIERE_TRANSMISION IN (0, 1)),
    CONSTRAINT CK_TORNEO_CAMARA CHECK (REQUIERE_CAMARA IN (0, 1)),
    CONSTRAINT FK_TORNEO_ANFITRION FOREIGN KEY (ANFITRION_ID) 
        REFERENCES USUARIO (ID),
    CONSTRAINT FK_TORNEO_JUEGO FOREIGN KEY (JUEGO_ID) 
        REFERENCES JUEGO (ID),
    CONSTRAINT FK_TORNEO_PLATAFORMA FOREIGN KEY (PLATAFORMA_ID) 
        REFERENCES CATALOGO_PLATAFORMA (ID),
    CONSTRAINT FK_TORNEO_MODO_JUEGO FOREIGN KEY (MODO_JUEGO_ID) 
        REFERENCES MODO_JUEGO (ID),
    CONSTRAINT FK_TORNEO_REGION FOREIGN KEY (REGION_ID) 
        REFERENCES CATALOGO_REGION (ID),
    CONSTRAINT FK_TORNEO_ESTADO FOREIGN KEY (ESTADO_ID) 
        REFERENCES CATALOGO_ESTADO_TORNEO (ID),
    CONSTRAINT FK_TORNEO_TIPO_TORNEO FOREIGN KEY (TIPO_TORNEO_ID) 
        REFERENCES CATALOGO_TIPO_TORNEO (ID),
    CONSTRAINT FK_TORNEO_TIPO_ENTRADA FOREIGN KEY (TIPO_ENTRADA_ID) 
        REFERENCES CATALOGO_TIPO_ENTRADA (ID)
);

CREATE TABLE TORNEO_INSCRIPCION (
    ID              NUMBER          NOT NULL,
    FECHA           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    TORNEO_ID       NUMBER,
    USUARIO_ID      NUMBER          NOT NULL,
    ESTADO_ID       NUMBER          NOT NULL,
    CONSTRAINT PK_TORNEO_INSCRIPCION PRIMARY KEY (ID),
    CONSTRAINT FK_INSCRIPCION_TORNEO FOREIGN KEY (TORNEO_ID) 
        REFERENCES TORNEO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_INSCRIPCION_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID),
    CONSTRAINT FK_INSCRIPCION_ESTADO FOREIGN KEY (ESTADO_ID) 
        REFERENCES CATALOGO_ESTADO_INSCRIPCION (ID)
);

CREATE TABLE TORNEO_PREMIOS (
    ID                      NUMBER          NOT NULL,
    CUOTA                   NUMBER,
    FONDO_TOTAL             NUMBER(12,2)    DEFAULT 0 NOT NULL,
    FONDO_DESPUES_COMISION  NUMBER(12,2)    DEFAULT 0 NOT NULL,
    COMISION_PORCENTAJE     NUMBER(5,2)     DEFAULT 0 NOT NULL,
    COMISION_TOTAL          NUMBER(12,2)    DEFAULT 0 NOT NULL,
    GANADOR1_PORCENTAJE     NUMBER(5,2)     DEFAULT 0 NOT NULL,
    GANADOR2_PORCENTAJE     NUMBER(5,2)     DEFAULT 0 NOT NULL,
    TORNEO_ID               NUMBER,
    CONSTRAINT PK_TORNEO_PREMIOS PRIMARY KEY (ID),
    CONSTRAINT UQ_TORNEO_PREMIOS_TORNEO UNIQUE (TORNEO_ID),
    CONSTRAINT FK_PREMIOS_TORNEO FOREIGN KEY (TORNEO_ID) 
        REFERENCES TORNEO (ID) ON DELETE CASCADE
);

CREATE TABLE TORNEO_REDES (
    ID              NUMBER          NOT NULL,
    PLATAFORMA      VARCHAR2(100)   NOT NULL,
    URL             VARCHAR2(500)   NOT NULL,
    TORNEO_ID       NUMBER,
    CONSTRAINT PK_TORNEO_REDES PRIMARY KEY (ID),
    CONSTRAINT FK_REDES_TORNEO FOREIGN KEY (TORNEO_ID) 
        REFERENCES TORNEO (ID) ON DELETE CASCADE
);

CREATE TABLE TORNEO_RESULTADOS (
    ID              NUMBER          NOT NULL,
    POSICION        NUMBER          NOT NULL,
    TORNEO_ID       NUMBER,
    USUARIO_ID      NUMBER,
    CONSTRAINT PK_TORNEO_RESULTADOS PRIMARY KEY (ID),
    CONSTRAINT FK_RESULTADOS_TORNEO FOREIGN KEY (TORNEO_ID) 
        REFERENCES TORNEO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESULTADOS_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID)
);

CREATE TABLE TRANSACCION (
    ID              NUMBER          NOT NULL,
    MONTO           NUMBER(12,2)    NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_ID      NUMBER,
    TIPO_ID         NUMBER          NOT NULL,
    ORIGEN_ID       NUMBER          NOT NULL,
    CONSTRAINT PK_TRANSACCION PRIMARY KEY (ID),
    CONSTRAINT FK_TRANSACCION_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TRANSACCION_TIPO FOREIGN KEY (TIPO_ID) 
        REFERENCES CATALOGO_TRANSACCION_TIPO (ID),
    CONSTRAINT FK_TRANSACCION_ORIGEN FOREIGN KEY (ORIGEN_ID) 
        REFERENCES CATALOGO_ORIGEN_TRANSACCION (ID)
);

CREATE TABLE USUARIO_AMIGOS (
    ID              NUMBER          NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO1_ID     NUMBER,
    USUARIO2_ID     NUMBER,
    ESTADO_ID       NUMBER          NOT NULL,
    CONSTRAINT PK_USUARIO_AMIGOS PRIMARY KEY (ID),
    CONSTRAINT FK_AMIGOS_USUARIO1 FOREIGN KEY (USUARIO1_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_AMIGOS_USUARIO2 FOREIGN KEY (USUARIO2_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_AMIGOS_ESTADO FOREIGN KEY (ESTADO_ID) 
        REFERENCES CATALOGO_ESTADO_AMISTAD (ID)
);

CREATE TABLE USUARIO_CUENTA_JUEGO (
    ID                  NUMBER          NOT NULL,
    IDENTIFICADOR       VARCHAR2(200)   NOT NULL,
    USUARIO_ID          NUMBER,
    PLATAFORMA_JUEGO_ID NUMBER          NOT NULL,
    CONSTRAINT PK_USUARIO_CUENTA_JUEGO PRIMARY KEY (ID),
    CONSTRAINT FK_CUENTA_JUEGO_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CUENTA_JUEGO_PLATAFORMA FOREIGN KEY (PLATAFORMA_JUEGO_ID) 
        REFERENCES CATALOGO_PLATAFORMA (ID)
);

CREATE TABLE USUARIO_ESTADISTICAS_JUEGO (
    ID              NUMBER          NOT NULL,
    VICTORIAS       NUMBER          DEFAULT 0 NOT NULL,
    DERROTAS        NUMBER          DEFAULT 0 NOT NULL,
    EMPATES         NUMBER          DEFAULT 0 NOT NULL,
    NIVEL_RANGO     VARCHAR2(100),
    HORAS_JUGADAS   NUMBER          DEFAULT 0 NOT NULL,
    ACTUALIZADO_EN  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_ID      NUMBER,
    JUEGO_ID        NUMBER,
    CONSTRAINT PK_USUARIO_ESTADISTICAS PRIMARY KEY (ID),
    CONSTRAINT FK_ESTADISTICAS_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID),
    CONSTRAINT FK_ESTADISTICAS_JUEGO FOREIGN KEY (JUEGO_ID) 
        REFERENCES JUEGO (ID)
);

CREATE TABLE USUARIO_LOGROS (
    ID              NUMBER          NOT NULL,
    FECHA           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_ID      NUMBER,
    LOGRO_ID        NUMBER,
    CONSTRAINT PK_USUARIO_LOGROS PRIMARY KEY (ID),
    CONSTRAINT FK_LOGROS_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_LOGROS_LOGRO FOREIGN KEY (LOGRO_ID) 
        REFERENCES LOGRO (ID)
);

CREATE TABLE USUARIO_MEMBRESIAS (
    ID              NUMBER          NOT NULL,
    FECHA_INICIO    DATE            NOT NULL,
    FECHA_FIN       DATE            NOT NULL,
    ACTIVA          NUMBER(1)       DEFAULT 1 NOT NULL,
    USUARIO_ID      NUMBER,
    MEMBRESIA_TIPO_ID NUMBER,
    CONSTRAINT PK_USUARIO_MEMBRESIAS PRIMARY KEY (ID),
    CONSTRAINT CK_MEMBRESIA_ACTIVA CHECK (ACTIVA IN (0, 1)),
    CONSTRAINT FK_MEMBRESIA_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBRESIA_TIPO FOREIGN KEY (MEMBRESIA_TIPO_ID) 
        REFERENCES MEMBRESIA_TIPO (ID)
);

CREATE TABLE USUARIO_RED_SOCIAL (
    ID              NUMBER          NOT NULL,
    PLATAFORMA      VARCHAR2(100)   NOT NULL,
    ENLACE          VARCHAR2(500)   NOT NULL,
    USUARIO_ID      NUMBER,
    CONSTRAINT PK_USUARIO_RED_SOCIAL PRIMARY KEY (ID),
    CONSTRAINT FK_RED_SOCIAL_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE
);

CREATE TABLE USUARIO_SEGUIDORES (
    ID              NUMBER          NOT NULL,
    CREADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    SEGUIDOR_ID     NUMBER,
    SEGUIDO_ID      NUMBER,
    CONSTRAINT PK_USUARIO_SEGUIDORES PRIMARY KEY (ID),
    CONSTRAINT FK_SEGUIDORES_SEGUIDOR FOREIGN KEY (SEGUIDOR_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SEGUIDORES_SEGUIDO FOREIGN KEY (SEGUIDO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE
);

CREATE TABLE USUARIO_TROFEOS (
    ID              NUMBER          NOT NULL,
    TIPO_TROFEO     VARCHAR2(100)   NOT NULL,
    GANADO_EN       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_ID      NUMBER,
    TORNEO_ID       NUMBER,
    CONSTRAINT PK_USUARIO_TROFEOS PRIMARY KEY (ID),
    CONSTRAINT FK_TROFEOS_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TROFEOS_TORNEO FOREIGN KEY (TORNEO_ID) 
        REFERENCES TORNEO (ID)
);


PROMPT >>> 39 Tablas creadas exitosamente <<<
